name: 'EAS build comment'
description: 'Comments output of EAS build to your PR'
author: 'Raul Steurer'
inputs:
  ghToken:
    required: true
    description: 'Github Token'
  json:
    required: true
    description: 'JSON output of build step'
runs:
  using: 'node16'
  main: 'dist/index.js'
